#!/usr/bin/env python
#-*-coding:utf8-*-

import jieba
import jieba.posseg as psg
import pandas as pd
import operator

words = {}

def ScanFile(file):
    file_data = pd.read_table('D:\\tmp\\'+file, sep = '|',index_col = 'com_buss_no')
    return file_data

def FilePro(file_data):
    for x in file_data['com_buss']:
        str = x.decode('utf8')
        #print str
        StringPro(str)
    return


def StringPro(str):
    global words
    for x in psg.cut(str):
        if ( words.has_key(x.word)):
            words[x.word] += 1
        else:
            if x.flag == 'x' or x.flag =='uj' or x.flag == 'c' or x.flag == 'p' or x.flag == 't':
                continue
            words[x.word] = 1
    return


def main():
    data = ScanFile('fo.txt')
    FilePro( data.ix['8290'])

    #print words
    #print words[u'教育']

    sorted_words = sorted( words.iteritems(), key=operator.itemgetter(1),reverse=True)
    print type(sorted_words)
    for x in sorted_words:
        print x[0],x[1]

    # for x in words.keys():
    #     print
    #print data['com_buss'][0]
    #str = data['com_buss'][0].decode('utf8')
    #print str
    #StringPro(str)
    #print words




    # s = u'根据珠海财政业务管理需要，提出国土出让金征收纳入非税收入管理系统统一管理，并要求土地出让资金能当天划入专户（当前一般非税收入是T+1日的模式）'
    # # cut = jieba.cut(s)
    # # cutstr =  ','.join(cut)
    # # cutpsg =  psg.cut(s)
    #
    # # print [(x.word, x.flag) for x in psg.cut(s)]
    #
    # # print cutstr.decode('utf')
    # # print cutstr
    # # print isinstance(cutstr, unicode)
    #
    # wordlist = []
    #
    # for x in psg.cut(s):
    #     #print x.word, x.flag
    #     wordlist.append(x.word)
    # print len(wordlist)
    #
    # print set(wordlist)
    # print isinstance(x.word[0],unicode)
    # print str(list(cut)).encode('utf8')

    # with  open('D:\\tmp\\word.txt','w') as f:
    #     for x in psg.cut(s):
    #         print x.flag
    #         f.writelines(x.word.encode('utf8')+ '|' + x.flag.encode('utf8') +"\n")
            # f.write(x.flag)
        # f.write(cutstr.encode('utf8'))
        # for word in x.word:
        #     f.write(word.encode('GBK'))


if __name__ == '__main__':
    # s = u'根据珠海财政业务管理需要，提出国土出让金征收纳入非税收入管理系统统一管理，并要求土地出让资金能当天划入专户（当前一般非税收入是T+1日的模式）'
    # for x in psg.cut(s):
    #     print x.word, x.flag
    main()